FROM alpine:3.22

LABEL maintainer="hareesh <hareesh.uk4839@gmail.com>"


ARG UID=1010
ARG GID=1010

# install prerequisites for public key and pkg-oss checks
RUN addgroup -g $GID -S appuser || true \
    && adduser -S -D -H -u $UID -h /var/cache/appuser -s /sbin/nologin -G appuser -g appuser appuser || true \
    && apk --no-cache upgrade && apk update && apk --no-cache add \
                binutils-gold \
                libstdc++ \
                g++ \
                gnupg \
                libgcc \
                gcc \
                libc-dev \
                pcre2-dev \
                zlib-dev \
                linux-headers \
                bash \
                alpine-sdk \
                findutils \
                curl \
                openssl \
                traceroute \
                busybox-extras \
                ca-certificates \
                yq \
                autoconf \
                automake \
                bzip2 \
                build-base \
                file \
                imagemagick \
                libbz2 \
                curl-dev \
                db-dev \
                libevent-dev \ 
                libffi-dev \
                gdbm-dev \
                glib-dev \
                gmp-dev \
                jpeg-dev \
                krb5-dev \
                xz-dev \
                libmaxminddb-dev \
                ncurses-dev \
                libpng-dev \
                postgresql-dev \
                readline-dev \
                sqlite-dev \
                openssl-dev \
                libtool \
                libwebp-dev \
                libxml2-dev \
                libxslt-dev \
                yaml-dev \
                make \
                patch \
                unzip \
                zlib-dev \
                git \
                jq \
                yq \
                tree \
                curl \
                tar \
                wget
ENV BASE_URL="https://get.helm.sh"
ENV VERSION=3.19.0
RUN case `uname -m` in \
        x86_64) ARCH=amd64; ;; \
        armv7l) ARCH=arm; ;; \
        aarch64) ARCH=arm64; ;; \
        ppc64le) ARCH=ppc64le; ;; \
        s390x) ARCH=s390x; ;; \
        *) echo "un-supported arch, exit ..."; exit 1; ;; \
    esac && \
    wget ${BASE_URL}/helm-v${VERSION}-linux-${ARCH}.tar.gz -O - | tar -xz && \
    mv linux-${ARCH}/helm /usr/bin/helm && \
    chmod +x /usr/bin/helm && \
    rm -rf linux-${ARCH}

# Install GitHub CLI
RUN update-ca-certificates && curl -s https://api.github.com/repos/cli/cli/releases/latest \
    | grep "browser_download_url.*linux_amd64\.tar\.gz" \
    | cut -d '"' -f 4 \
    | xargs curl -L -o gh.tar.gz && \
    tar -xzf gh.tar.gz && \
    mv gh_*/bin/gh /usr/local/bin/ && \
    rm -rf gh.tar.gz gh_* && git --version && gh --version

USER $UID