FROM python:3.10.18-bookworm
LABEL maintainer="hareesh"

ENV PYTHON_VERSION=3.10.18 \
    UID=1010 \
    USER=appuser

RUN set -eux; \
	\
	apt-get update -y ; \
	apt-get upgrade -y ; \
	apt-get install -y --no-install-recommends \
	    ca-certificates \
		netbase \
		tzdata \
		dpkg-dev \
		gcc \
		gnupg \
		bash \
		traceroute \
        net-tools \
        curl \
		jq yq

RUN adduser \
    --disabled-password \
	--gecos "" \
	--no-create-home \
	--uid "$UID" \
	--shell "/bin/bash" \
	$USER

USER 1010
CMD ["python3"]