FROM node:22.17.0-alpine3.21

LABEL maintainer="hareesh"

ENV NODE_VERSION=22.12.0 \
    UID=1000 \
    USER=app-user
RUN     apk update && \
        apk upgrade && \
        apk add --no-cache \
        bash \
        ca-certificates \
        traceroute \
        busybox-extras \
        curl \
        yq

         
USER 1000
CMD [ "node" ]