FROM python:3.12.8-slim-bookworm
LABEL maintainer="hareesh"

ENV PYTHON_VERSION=3.12.8 \
    UID=1000 \
    USER=app-user

RUN set -eux; \
	\
	apt-get update; \
	apt-get upgrade; \
	apt-get install -y --no-install-recommends \
	    ca-certificates \
		netbase \
		tzdata \
		dpkg-dev \
		gcc \
		gnupg \
		bash \
		traceroute \
        net-tools \
        dnsutils \
        curl

RUN adduser \
    --disabled-password \
	--gecos "" \
	--no-create-home \
	--uid "$UID" \
	--shell "/bin/bash" \
	$USER

USER 1000
CMD ["python3"]